# Generated by Django 5.1.2 on 2024-11-26 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_post_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
