# Generated by Django 5.1.2 on 2024-12-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hook_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
